# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  SET_CODE: "lea"
  BINARY_PATH: './artisan-doubleton-generator'

tasks:
  build:
    aliases: [default]
    sources:
      - '*.go'
      - 'go.mod'
    generates:
      - "{{ .BINARY_PATH }}"
    cmd: go build -o "{{ .BINARY_PATH }}" ./...
  run:
    deps: [build]
    cmd: "{{ .BINARY_PATH }} {{ .SET_CODE }}"
  build-docker:
    cmd: docker build -t artisan-doubleton-generator .
  run-docker:
    deps: [build-docker]
    cmd: docker run --rm -v "${PWD}:/work" -w /work artisan-doubleton-generator {{ .SET_CODE }}
