# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  BINARY_PATH: './cubecobra-price-checker'
  DEFAULT_BULK_DATA_API_URL: "https://api.scryfall.com/bulk-data/default-cards"
  DEFAULT_BULK_DATA_PATH: DefaultCards.json
  DEFAULT_BULK_DATA_API_CONTENTS:
    sh: curl -s {{ .DEFAULT_BULK_DATA_API_URL }}
  DEFAULT_BULK_DATA_API_CONTENTS_PARSED:
    ref: 'fromJson .DEFAULT_BULK_DATA_API_CONTENTS'

tasks:
  build:
    aliases: [default]
    sources:
      - '*.go'
    generates:
      - "{{ .BINARY_PATH }}"
    cmd: go build -o "{{ .BINARY_PATH }}" ./...
  run:
    deps: [build]
    requires:
      vars: [CUBE_ID]
    cmd: "{{ .BINARY_PATH }} {{ .CUBE_ID }}"
  download-data:
    status:
      - test $(find {{ .DEFAULT_BULK_DATA_PATH }} -mmin +720)
    cmd: curl -o {{ .DEFAULT_BULK_DATA_PATH }} {{ .DEFAULT_BULK_DATA_API_CONTENTS_PARSED.download_uri }}
  build-docker:
    cmd: docker build -t cubecobra-price-checker .
  run-docker:
    deps: [download-data, build-docker]
    requires:
      vars: [CUBE_ID]
    cmd: docker run cubecobra-price-checker {{ .CUBE_ID }}
    
