name: CubeCobra Cube Price Calculator

on:
  schedule:
    # Run every 3 months
    - cron: '0 0 1 */3 *'
  workflow_dispatch:
    inputs:
      cube_id:
        description: "CubeCobra cube ID"
        required: false
        default: "d8b9e896-d66d-4cf8-9c59-f752d78d27ac"
        type: string

jobs:
  calculate-price:
    name: Calculate Total Cube Price
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate cube total cost
        uses: ./cubecobra-price
        with:
          cube_id: ${{ inputs.cube_id || 'd8b9e896-d66d-4cf8-9c59-f752d78d27ac' }}
